name: TODO_List_CI/CD Pipeline

on:
    push:
      branches:
        - main  # Runs the pipeline on push events to the main branch
    pull_request:
      branches:
        - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu VM in the GitHub Actions environment

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version: '1.22'  # Set the Go version
    
      # Step 3: Install dependencies
      - name: Install Go dependencies
        run: go mod tidy

      # Step 6: Build the Go application
      - name: Build Go application
        run: go build -o todo-app .

      # Step 4: Set Environment Variables
      - name: Set environment variables
        run: |
          IFS=';' read -r -a array <<< "${{ secrets.TODO_LIST_POSTGRESQL_ENV }}"
          for item in "${array[@]}"; do
            # Split each item into a key and value
            key="${item%%=*}"
            value="${item#*=}"
            # Export as an environment variable
            export "$key=$value"
          done

      # Step 7: Run the Go application (optional for local testing)
        - name: Run Go application
          env:
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_NAME: ${{ secrets.DB_NAME }}
          run: |
            go run main.go
            echo "Running the Go application..."