name: TODO_List_CI/CD Pipeline

on:
    push:
      branches:
        - main  # Runs the pipeline on push events to the main branch
    pull_request:
      branches:
        - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu VM in the GitHub Actions environment

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version: '1.22'  # Set the Go version
    
      # Step 3: Install dependencies
      - name: Install Go dependencies
        run: go mod tidy

      # Step 4: Build the Go application
      - name: Build Go application
        run: go build -o todo-app .